# Generated by Django 3.1.6 on 2021-02-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210216_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='board',
            new_name='category',
        ),
    ]
