# Generated by Django 3.1.6 on 2021-02-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210217_0923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
