# Generated by Django 3.1.6 on 2021-02-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='img',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
